jenkins:
  hosts: 
    server:
      ansible_host: ec2-65-2-38-209.ap-south-1.compute.amazonaws.com
      ansible_user: ubuntu
jenkins_agent:
  hosts:
    agent_one:
      ansible_host: ec2-3-110-85-152.ap-south-1.compute.amazonaws.com
      ansible_user: ubuntu