jenkins:
  hosts: 
    server:
      ansible_host: ec2-65-2-39-113.ap-south-1.compute.amazonaws.com
      ansible_user: ubuntu
jenkins_agent:
  hosts:
    agent_one:
      ansible_host: ec2-52-66-62-144.ap-south-1.compute.amazonaws.com
      ansible_user: ubuntu