apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/created-by: nihar
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
  ports:
  - port: 8181
    targetPort: 8181
