apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/created-by: nihar
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app }}
  ports:
  - port: 8282
    targetPort: 8000
